// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParallelWorld.Infrastructure.Persistence;

#nullable disable

namespace ParallelWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ParallelWorldDbContext))]
    [Migration("20260831162301_InitialM03")]
    partial class InitialM03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.DeviceInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InstallationPublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("installation_public_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_installations");

                    b.HasAlternateKey("UserId", "Id")
                        .HasName("ak_device_installations_user_id_id");

                    b.HasIndex("InstallationPublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_device_installations_public_id");

                    b.HasIndex("UserId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_device_installations_user_last_seen");

                    b.ToTable("device_installations", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.GuestBootstrapOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_installation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProofHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("proof_hash");

                    b.Property<DateTimeOffset?>("RecoveryConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_consumed_at");

                    b.Property<Guid>("RefreshTokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_bootstrap_operations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_bootstrap_operations_expires_at");

                    b.HasIndex("ProofHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_bootstrap_operations_proof_hash");

                    b.HasIndex("UserId", "DeviceInstallationId")
                        .HasDatabaseName("ix_guest_bootstrap_operations_user_device");

                    b.ToTable("guest_bootstrap_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_guest_bootstrap_operations_expiry", "expires_at > completed_at");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_installation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("RotationFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("rotation_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("RotationFamilyId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_family_expiry");

                    b.HasIndex("UserId", "DeviceInstallationId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_device_expiry");

                    b.HasIndex("UserId", "RotationFamilyId", "CreatedAt", "RevokedAt", "ConsumedAt", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_family_created_state");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_actors_world_id_id");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_character_id")
                        .HasFilter("character_id IS NOT NULL");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_player_profile_id")
                        .HasFilter("player_profile_id IS NOT NULL");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_one_player_per_world")
                        .HasFilter("actor_type = 'player'");

                    b.HasIndex("WorldId", "PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_world_player_profile");

                    b.ToTable("actors", null, t =>
                        {
                            t.HasCheckConstraint("ck_actors_detail_shape", "(actor_type = 'player' AND player_profile_id IS NOT NULL AND character_id IS NULL) OR (actor_type = 'character' AND player_profile_id IS NULL AND character_id IS NOT NULL) OR (actor_type = 'system' AND player_profile_id IS NULL AND character_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.GameWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentWorldTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_world_time");

                    b.Property<DateTimeOffset>("LastSimulatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_simulated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_game_worlds");

                    b.HasAlternateKey("OwnerUserId", "Id")
                        .HasName("ak_game_worlds_owner_user_id_id");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("ix_game_worlds_owner_status");

                    b.HasIndex("OwnerUserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_game_worlds_owner_created");

                    b.ToTable("game_worlds", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer")
                        .HasColumnName("followers_count");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("handle");

                    b.Property<int>("Influence")
                        .HasColumnType("integer")
                        .HasColumnName("influence");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_player_profiles");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_player_profiles_world_id_id");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_world_id");

                    b.HasIndex("WorldId", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_world_handle");

                    b.ToTable("player_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_profiles_followers", "followers_count >= 0");

                            t.HasCheckConstraint("ck_player_profiles_influence", "influence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_player_profiles_reputation", "reputation BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("action_limit");

                    b.Property<int>("AiBudgetTokens")
                        .HasColumnType("integer")
                        .HasColumnName("ai_budget_tokens");

                    b.Property<string>("ContentSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_settings");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version");

                    b.Property<decimal>("TimeScale")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("time_scale");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_settings");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_settings_world_id");

                    b.ToTable("world_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_world_settings_action_limit", "action_limit >= 0");

                            t.HasCheckConstraint("ck_world_settings_ai_budget", "ai_budget_tokens >= 0");

                            t.HasCheckConstraint("ck_world_settings_time_scale", "time_scale > 0");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSimulationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeterministicSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("deterministic_sequence");

                    b.Property<DateTimeOffset?>("LastCompletedIntervalEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_interval_end");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_simulation_states");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_simulation_states_world_id");

                    b.ToTable("world_simulation_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_world_simulation_states_sequence", "deterministic_sequence >= 0");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.DeviceInstallation", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_installations_users_user_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.GuestBootstrapOperation", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_bootstrap_operations_users_user_id");

                    b.HasOne("ParallelWorld.Domain.Accounts.DeviceInstallation", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DeviceInstallationId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_bootstrap_operations_installations_user_device");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.RefreshToken", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.RefreshToken", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Accounts.RefreshToken", "ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_replacement");

                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.HasOne("ParallelWorld.Domain.Accounts.DeviceInstallation", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DeviceInstallationId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_installations_user_device");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.Actor", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actors_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.PlayerProfile", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.Actor", "WorldId", "PlayerProfileId")
                        .HasPrincipalKey("ParallelWorld.Domain.Worlds.PlayerProfile", "WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actors_player_profiles_world_profile");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.GameWorld", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_worlds_users_owner_user_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.PlayerProfile", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.PlayerProfile", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_profiles_game_worlds_world_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSettings", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.WorldSettings", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_world_settings_game_worlds_world_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSimulationState", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.WorldSimulationState", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_world_simulation_states_game_worlds_world_id");
                });
#pragma warning restore 612, 618
        }
    }
}
