// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParallelWorld.Infrastructure.Persistence;

#nullable disable

namespace ParallelWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ParallelWorldDbContext))]
    [Migration("20260916132321_AddM07SocialActions")]
    partial class AddM07SocialActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.DeviceInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InstallationPublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("installation_public_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_installations");

                    b.HasAlternateKey("UserId", "Id")
                        .HasName("ak_device_installations_user_id_id");

                    b.HasIndex("InstallationPublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_device_installations_public_id");

                    b.HasIndex("UserId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_device_installations_user_last_seen");

                    b.ToTable("device_installations", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.GuestBootstrapOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_installation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProofHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("proof_hash");

                    b.Property<DateTimeOffset?>("RecoveryConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_consumed_at");

                    b.Property<Guid>("RefreshTokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_bootstrap_operations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_bootstrap_operations_expires_at");

                    b.HasIndex("ProofHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_bootstrap_operations_proof_hash");

                    b.HasIndex("UserId", "DeviceInstallationId")
                        .HasDatabaseName("ix_guest_bootstrap_operations_user_device");

                    b.ToTable("guest_bootstrap_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_guest_bootstrap_operations_expiry", "expires_at > completed_at");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_installation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("RotationFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("rotation_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("RotationFamilyId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_family_expiry");

                    b.HasIndex("UserId", "DeviceInstallationId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_device_expiry");

                    b.HasIndex("UserId", "RotationFamilyId", "CreatedAt", "RevokedAt", "ConsumedAt", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_family_created_state");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("activity_level");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("archetype");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentMoodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_mood_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("handle");

                    b.Property<int>("Influence")
                        .HasColumnType("integer")
                        .HasColumnName("influence");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("profession");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("WritingStyle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("writing_style");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_characters_world_id_id");

                    b.HasIndex("WorldId", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_world_handle");

                    b.HasIndex("WorldId", "Status", "Id")
                        .HasDatabaseName("ix_characters_world_status_id");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_activity_level", "activity_level BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_characters_age", "age >= 0");

                            t.HasCheckConstraint("ck_characters_influence", "influence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_characters_popularity", "popularity BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_character_interests");

                    b.HasIndex("WorldId", "CharacterId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ux_character_interests_world_character_topic");

                    b.ToTable("character_interests", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_interests_strength", "strength BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterOpinion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer")
                        .HasColumnName("intensity");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_character_opinions");

                    b.HasIndex("WorldId", "CharacterId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ux_character_opinions_world_character_topic");

                    b.ToTable("character_opinions", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_opinions_confidence", "confidence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_opinions_intensity", "intensity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_opinions_position", "position BETWEEN -100 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_local_time");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_character_schedules");

                    b.HasIndex("WorldId", "CharacterId", "DayOfWeek", "StartLocalTime")
                        .HasDatabaseName("ix_character_schedules_world_character_day_start");

                    b.ToTable("character_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_schedules_day", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_character_schedules_time", "end_local_time > start_local_time");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Aggression")
                        .HasColumnType("integer")
                        .HasColumnName("aggression");

                    b.Property<int>("Ambition")
                        .HasColumnType("integer")
                        .HasColumnName("ambition");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Curiosity")
                        .HasColumnType("integer")
                        .HasColumnName("curiosity");

                    b.Property<int>("Empathy")
                        .HasColumnType("integer")
                        .HasColumnName("empathy");

                    b.Property<int>("Honesty")
                        .HasColumnType("integer")
                        .HasColumnName("honesty");

                    b.Property<int>("Humour")
                        .HasColumnType("integer")
                        .HasColumnName("humour");

                    b.Property<int>("Optimism")
                        .HasColumnType("integer")
                        .HasColumnName("optimism");

                    b.Property<int>("Patience")
                        .HasColumnType("integer")
                        .HasColumnName("patience");

                    b.Property<int>("RomanticOpenness")
                        .HasColumnType("integer")
                        .HasColumnName("romantic_openness");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("integer")
                        .HasColumnName("sensitivity");

                    b.Property<int>("Sociability")
                        .HasColumnType("integer")
                        .HasColumnName("sociability");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_character_traits");

                    b.HasIndex("WorldId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_character_traits_world_character");

                    b.ToTable("character_traits", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_traits_aggression", "aggression BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_ambition", "ambition BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_confidence", "confidence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_curiosity", "curiosity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_empathy", "empathy BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_honesty", "honesty BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_humour", "humour BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_optimism", "optimism BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_patience", "patience BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_romantic_openness", "romantic_openness BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_sensitivity", "sensitivity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_character_traits_sociability", "sociability BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("FollowedActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("followed_actor_id");

                    b.Property<Guid>("FollowerActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_actor_id");

                    b.Property<Guid>("GameplayEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("gameplay_event_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_follows");

                    b.HasIndex("WorldId", "GameplayEventId")
                        .HasDatabaseName("ix_follows_world_gameplay_event");

                    b.HasIndex("WorldId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_follows_world_idempotency_key");

                    b.HasIndex("WorldId", "FollowedActorId", "EndedAt")
                        .HasDatabaseName("ix_follows_world_followed_ended");

                    b.HasIndex("WorldId", "FollowerActorId", "EndedAt")
                        .HasDatabaseName("ix_follows_world_follower_ended");

                    b.HasIndex("WorldId", "FollowerActorId", "FollowedActorId")
                        .IsUnique()
                        .HasDatabaseName("ux_follows_world_follower_followed_active")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("follows", null, t =>
                        {
                            t.HasCheckConstraint("ck_follows_distinct_actors", "follower_actor_id <> followed_actor_id");

                            t.HasCheckConstraint("ck_follows_time", "ended_at IS NULL OR ended_at >= started_at");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.GameplayEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmotionalImpact")
                        .HasColumnType("integer")
                        .HasColumnName("emotional_impact");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version");

                    b.Property<Guid?>("TargetActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_actor_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_gameplay_events");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_gameplay_events_world_id_id");

                    b.HasIndex("WorldId", "ActorId")
                        .HasDatabaseName("ix_gameplay_events_world_actor");

                    b.HasIndex("WorldId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_gameplay_events_world_idempotency_key");

                    b.HasIndex("WorldId", "TargetActorId")
                        .HasDatabaseName("ix_gameplay_events_world_target");

                    b.HasIndex("WorldId", "EventType", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_gameplay_events_world_type_occurred");

                    b.HasIndex("WorldId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_gameplay_events_world_occurred_id");

                    b.ToTable("gameplay_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_gameplay_events_actor_target", "actor_id IS NULL OR target_actor_id IS NULL OR actor_id <> target_actor_id");

                            t.HasCheckConstraint("ck_gameplay_events_emotional_impact", "emotional_impact BETWEEN -100 AND 100");

                            t.HasCheckConstraint("ck_gameplay_events_importance", "importance BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<Guid>("ResponseResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_resource_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_status_expires");

                    b.HasIndex("UserId", "WorldId")
                        .HasDatabaseName("ix_idempotency_records_user_world");

                    b.HasIndex("UserId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_user_operation_key");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_response_code", "response_code >= 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_actor_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GameplayEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("gameplay_event_id");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<Guid?>("ParentPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_post_id");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer")
                        .HasColumnName("reply_count");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_posts_world_id_id");

                    b.HasIndex("WorldId", "GameplayEventId")
                        .HasDatabaseName("ix_posts_world_gameplay_event");

                    b.HasIndex("WorldId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_posts_world_created_id_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("WorldId", "AuthorActorId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_posts_world_author_created_id_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("WorldId", "ParentPostId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_posts_world_parent_created_id_active")
                        .HasFilter("parent_post_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("posts", null, t =>
                        {
                            t.HasCheckConstraint("ck_posts_like_count", "like_count >= 0");

                            t.HasCheckConstraint("ck_posts_not_self_parent", "parent_post_id IS NULL OR parent_post_id <> id");

                            t.HasCheckConstraint("ck_posts_reply_count", "reply_count >= 0");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.PostReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameplayEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("gameplay_event_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reaction_type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_post_reactions");

                    b.HasIndex("WorldId", "ActorId")
                        .HasDatabaseName("ix_post_reactions_world_actor");

                    b.HasIndex("WorldId", "GameplayEventId")
                        .HasDatabaseName("ix_post_reactions_world_gameplay_event");

                    b.HasIndex("WorldId", "PostId", "ActorId", "ReactionType")
                        .IsUnique()
                        .HasDatabaseName("ux_post_reactions_world_post_actor_type");

                    b.HasIndex("WorldId", "PostId", "ReactionType", "CreatedAt", "Id")
                        .HasDatabaseName("ix_post_reactions_world_post_type_created_id");

                    b.ToTable("post_reactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_post_reactions_type", "reaction_type = 'like'");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_actors_world_id_id");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_character_id")
                        .HasFilter("character_id IS NOT NULL");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_player_profile_id")
                        .HasFilter("player_profile_id IS NOT NULL");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_one_player_per_world")
                        .HasFilter("actor_type = 'player'");

                    b.HasIndex("WorldId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_world_character");

                    b.HasIndex("WorldId", "PlayerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_actors_world_player_profile");

                    b.ToTable("actors", null, t =>
                        {
                            t.HasCheckConstraint("ck_actors_detail_shape", "(actor_type = 'player' AND player_profile_id IS NOT NULL AND character_id IS NULL) OR (actor_type = 'character' AND player_profile_id IS NULL AND character_id IS NOT NULL) OR (actor_type = 'system' AND player_profile_id IS NULL AND character_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.GameWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentWorldTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_world_time");

                    b.Property<DateTimeOffset>("LastSimulatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_simulated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_game_worlds");

                    b.HasAlternateKey("OwnerUserId", "Id")
                        .HasName("ak_game_worlds_owner_user_id_id");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("ix_game_worlds_owner_status");

                    b.HasIndex("OwnerUserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_game_worlds_owner_created");

                    b.ToTable("game_worlds", (string)null);
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer")
                        .HasColumnName("followers_count");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("handle");

                    b.Property<int>("Influence")
                        .HasColumnType("integer")
                        .HasColumnName("influence");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_player_profiles");

                    b.HasAlternateKey("WorldId", "Id")
                        .HasName("ak_player_profiles_world_id_id");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_world_id");

                    b.HasIndex("WorldId", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_world_handle");

                    b.ToTable("player_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_profiles_followers", "followers_count >= 0");

                            t.HasCheckConstraint("ck_player_profiles_influence", "influence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_player_profiles_reputation", "reputation BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("action_limit");

                    b.Property<int>("AiBudgetTokens")
                        .HasColumnType("integer")
                        .HasColumnName("ai_budget_tokens");

                    b.Property<string>("ContentSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_settings");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version");

                    b.Property<decimal>("TimeScale")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("time_scale");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_settings");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_settings_world_id");

                    b.ToTable("world_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_world_settings_action_limit", "action_limit >= 0");

                            t.HasCheckConstraint("ck_world_settings_ai_budget", "ai_budget_tokens >= 0");

                            t.HasCheckConstraint("ck_world_settings_time_scale", "time_scale > 0");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSimulationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeterministicSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("deterministic_sequence");

                    b.Property<DateTimeOffset?>("LastCompletedIntervalEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_interval_end");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_simulation_states");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_simulation_states_world_id");

                    b.ToTable("world_simulation_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_world_simulation_states_sequence", "deterministic_sequence >= 0");
                        });
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.DeviceInstallation", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_installations_users_user_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.GuestBootstrapOperation", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_bootstrap_operations_users_user_id");

                    b.HasOne("ParallelWorld.Domain.Accounts.DeviceInstallation", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DeviceInstallationId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_bootstrap_operations_installations_user_device");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Accounts.RefreshToken", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.RefreshToken", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Accounts.RefreshToken", "ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_replacement");

                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.HasOne("ParallelWorld.Domain.Accounts.DeviceInstallation", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DeviceInstallationId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_installations_user_device");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.Character", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_characters_game_worlds_world_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterInterest", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "CharacterId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_interests_characters_world_character");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterOpinion", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "CharacterId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_opinions_characters_world_character");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterSchedule", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "CharacterId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_schedules_characters_world_character");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Characters.CharacterTraits", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "CharacterId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_traits_characters_world_character");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.Follow", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "FollowedActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_actors_world_followed");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "FollowerActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_actors_world_follower");

                    b.HasOne("ParallelWorld.Domain.Social.GameplayEvent", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "GameplayEventId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_gameplay_events_world_event");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.GameplayEvent", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gameplay_events_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "ActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gameplay_events_actors_world_actor");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "TargetActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gameplay_events_actors_world_target");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.IdempotencyRecord", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_users_user_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("UserId", "WorldId")
                        .HasPrincipalKey("OwnerUserId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_idempotency_records_game_worlds_user_world");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.Post", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "AuthorActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_actors_world_author");

                    b.HasOne("ParallelWorld.Domain.Social.GameplayEvent", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "GameplayEventId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_gameplay_events_world_event");

                    b.HasOne("ParallelWorld.Domain.Social.Post", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "ParentPostId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_posts_posts_world_parent");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Social.PostReaction", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_reactions_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Worlds.Actor", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "ActorId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_reactions_actors_world_actor");

                    b.HasOne("ParallelWorld.Domain.Social.GameplayEvent", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "GameplayEventId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_reactions_gameplay_events_world_event");

                    b.HasOne("ParallelWorld.Domain.Social.Post", null)
                        .WithMany()
                        .HasForeignKey("WorldId", "PostId")
                        .HasPrincipalKey("WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_reactions_posts_world_post");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.Actor", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actors_game_worlds_world_id");

                    b.HasOne("ParallelWorld.Domain.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.Actor", "WorldId", "CharacterId")
                        .HasPrincipalKey("ParallelWorld.Domain.Characters.Character", "WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actors_characters_world_character");

                    b.HasOne("ParallelWorld.Domain.Worlds.PlayerProfile", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.Actor", "WorldId", "PlayerProfileId")
                        .HasPrincipalKey("ParallelWorld.Domain.Worlds.PlayerProfile", "WorldId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actors_player_profiles_world_profile");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.GameWorld", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_worlds_users_owner_user_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.PlayerProfile", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.PlayerProfile", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_profiles_game_worlds_world_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSettings", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.WorldSettings", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_world_settings_game_worlds_world_id");
                });

            modelBuilder.Entity("ParallelWorld.Domain.Worlds.WorldSimulationState", b =>
                {
                    b.HasOne("ParallelWorld.Domain.Worlds.GameWorld", null)
                        .WithOne()
                        .HasForeignKey("ParallelWorld.Domain.Worlds.WorldSimulationState", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_world_simulation_states_game_worlds_world_id");
                });
#pragma warning restore 612, 618
        }
    }
}
