namespace ParallelWorld.Domain.Relationships;

public static class RelationshipMechanics
{
    public const int OrdinaryEventCap = 15; public const int SevereEventCap = 30; public const int OrdinaryDailyCap = 20;
    public static int InterestOverlap(IEnumerable<string> left, IEnumerable<string> right) { var a = left.ToHashSet(StringComparer.Ordinal); var b = right.ToHashSet(StringComparer.Ordinal); if (a.Count == 0 || b.Count == 0) return 0; return (int)Math.Round(100m * a.Intersect(b).Count() / a.Union(b).Count(), MidpointRounding.AwayFromZero); }
    public static int Relevance(RelationshipValues v) => Math.Clamp((int)Math.Round(.25m * v.Familiarity + .15m * v.Trust + .15m * v.Respect + .15m * v.Affection + .10m * v.Comfort + .10m * v.Rivalry + .05m * v.Jealousy + .025m * v.Attraction + .025m * v.Commitment, MidpointRounding.AwayFromZero), 0, 100);
    public static string Label(RelationshipValues v) => v.Rivalry >= 75 && v.Trust <= 20 && v.Affection <= 20 ? "enemy" : v.Rivalry >= 60 ? "rival" : v.Familiarity >= 80 && v.Trust >= 80 && v.Affection >= 75 && v.Comfort >= 70 && v.Rivalry < 25 ? "best_friend" : v.Familiarity >= 65 && v.Trust >= 65 && v.Affection >= 60 && v.Comfort >= 55 && v.Rivalry < 40 ? "close_friend" : v.Familiarity >= 40 && v.Trust >= 40 && v.Affection >= 35 && v.Rivalry < 50 ? "friend" : v.Familiarity >= 15 ? "acquaintance" : "stranger";
    public static int FollowProbability(RelationshipValues v, int interestOverlap, int reputation) => Math.Clamp((int)Math.Round(.25m * v.Familiarity + .25m * interestOverlap + .20m * v.Trust + .15m * v.Affection + .15m * reputation, MidpointRounding.AwayFromZero), 0, 100);
    public static RelationshipValues ApplyModifiers(RelationshipValues b, bool publicNegative, int priorPositive) { decimal repetition = priorPositive >= 3 ? .5m : 1m; int Scale(int x, bool context) => Math.Sign(x) * Math.Min(OrdinaryEventCap, (int)Math.Round(Math.Abs(x) * repetition * (context ? 1.25m : 1m), MidpointRounding.AwayFromZero)); return new(Scale(b.Familiarity, false), Scale(b.Trust, false), Scale(b.Respect, publicNegative && b.Respect < 0), Scale(b.Affection, false), Scale(b.Comfort, false), Scale(b.Rivalry, publicNegative && b.Rivalry > 0), Scale(b.Jealousy, false), Scale(b.Attraction, false), Scale(b.Commitment, false)); }
    public static RelationshipValues ApplyDailyCap(RelationshipValues d, RelationshipValues used) { int Cap(int x, int u) => Math.Sign(x) * Math.Min(Math.Abs(x), Math.Max(0, OrdinaryDailyCap - u)); return new(Cap(d.Familiarity, used.Familiarity), Cap(d.Trust, used.Trust), Cap(d.Respect, used.Respect), Cap(d.Affection, used.Affection), Cap(d.Comfort, used.Comfort), Cap(d.Rivalry, used.Rivalry), Cap(d.Jealousy, used.Jealousy), Cap(d.Attraction, used.Attraction), Cap(d.Commitment, used.Commitment)); }
}
